## Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia

os:
  - linux

dist: xenial

if: branch = master OR tag IS present OR type = pull_request

julia:
  - 1.0
  - 1.4
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

codecov: true
